Feature/mudar relacionamento entre tabelas estoque e produto
AndreLFernandesDev/GestorDeEstoque pull request #16
Opened 2024-11-13 04:51 UTC by AndreLFernandesDev

2024-11-15 19:00 UTC, mayconfsousa requested changes

2024-11-15 19:00 UTC, mayconfsousa commented on GestorDeEstoque/Models/Produto.cs
>          public decimal Quantidade { get; set; }
Vai precisar remover a quantidade daqui e dos lugares aonde esse campo é usado, porque ele foi movido para a tabela nova

```suggestion
```

2024-11-27 10:38 UTC, mayconfsousa requested changes

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Data/ApplicationDbContext.cs
> +            ProdutosEstoques = Set<ProdutoEstoque>();
Porque precisou de inicializar essa variáveis aqui?
Por exemplo, `Produtos` já existia e não era inicializada aqui.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Models/LogEstoque.cs
> +        public int IdEstoque { get; set; } = idEstoque;
Faltou o `virtual Estoque` aqui, imagino.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Models/ProdutoEstoque.cs
> +        public Produto? Produto { get; set; }
`Produto` e `Estoque` não deveria ser nullable aqui. Acho que deveria ser `virtual` também. O que acha?

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
> +    });
Para que serve essa config nova aqui?

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/EstoqueRepository.cs
> +            var quantidadeProduto = await _context.ProdutosEstoques.FirstOrDefaultAsync(qp => qp.ProdutoId == idProduto && qp.EstoqueId == idEstoque);
Essa variável `quantidadeProduto` deveria chamar `produtoEstoque`  ou algo assim, porque ela representa um item da tabela `ProdutoEstoque` e não apenas a quantidade. Pelo nome eu vou achar que é um número, mas não é.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +            var produtoQuantidade = await _context.ProdutosEstoques.FirstOrDefaultAsync(pq => pq.ProdutoId == idProduto && pq.EstoqueId == idEstoque);
Ajustar o nome `produtoQuantidade`

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +            var produtoExistente = await _context.ProdutosEstoques.FirstOrDefaultAsync(pe => pe.ProdutoId == produtoEstoque.ProdutoId && pe.EstoqueId == produtoEstoque.EstoqueId);
Ajustar o nome `produtoExistente`

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +            var quantidadeProduto = await _context.ProdutosEstoques.FirstOrDefaultAsync(qP => qP.ProdutoId == idProduto && qP.EstoqueId == idEstoque);
Ajustar o nome `quantidadeProduto`

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +        public async Task<ProdutoEstoque> BuscarQuantidadePorIdAsync(int idProduto, int idEstoque)
Ajustar o nome `BuscarQuantidadePorIdAsync`. Pelo nome parece que preicsa passar um ID apenas mas o método recebe 2, e o retorno parece que vai retornar a quantidade mas está retornando um `ProdutoEstoque`

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +        public async Task<ProdutoEstoque> AdicionarQuantidadeAsync(ProdutoEstoque produtoEstoque)
Esse método está retornando `produtoEstoque` com quantidade atualizada?
Confirma se precisa desse retorno em algum lugar, senão pode retornar void.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoRepository.cs
> +            var estoque = await _context.Estoques.FirstOrDefaultAsync(e => e.Id == estoqueId);
A variável `estoque` não está sendo usada efetivamente na atualização do produto. Apenas na validação. Talvez não precise dela aqui.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoRepository.cs
> +            return produtoAtualizado;
Está retornando o mesmo parâmetro que entrou, me pergunto se precisa desse retorno mesmo.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoRepository.cs
> +        public async Task<ProdutoDTO> BuscarProdutoPorIdAsync(int idProduto, int idEstoque)
Ajustar o nome do método. Chama buscar por ID mas recebe 2 IDs.

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/bruno/Listar Produtos.bru
> +  url: {{URL_PADRAO}}/produtos/estoqueId/1
Não é um bom padrão REST nesse caso, passar `estoqueId` como `path parameter`, é melhor para como `query parameter` ou alterar a rota.

/produtos/estoqueId/1 ---> não OK
/produtos?estoqueId=1 ---> OK
/estoque/1/produtos/1 ---> OK porque produtos está dentro de estoque
/produtos/1 ---> OK também para pegar um produto específico

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/bruno/Deletar produto.bru
> +  url: {{URL_PADRAO}}/produtos/48/estoqueId/1
Usar query parameter aqui ou mudar a rota

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/bruno/Atualizar quantidade estoque.bru
> +  url: {{URL_PADRAO}}/estoque/49/idEstoque/2
Alterar a rota aqui. Pela rota parece que 49 é o ID do estoque e 2 é ID do estoque também

2024-11-27 10:38 UTC, mayconfsousa commented on GestorDeEstoque/bruno/Atualizar produto.bru
> +  url: {{URL_PADRAO}}/produtos/48/estoqueId/1
Ajustar rota

2024-12-03 00:20 UTC, AndreLFernandesDev commented on GestorDeEstoque/Data/ApplicationDbContext.cs
> +            ProdutosEstoques = Set<ProdutoEstoque>();
Para o funcionamento do código não é necessário inicializá-las, mas acaba gerando observações de possíveis valores nulos, por isso, optei por inicializar

2024-12-03 00:40 UTC, AndreLFernandesDev commented on GestorDeEstoque/Program.cs
> +    });
É usado para evitar ciclos infinitos durante a serialização

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/ProdutoController.cs
> +                await _produtoEstoqueRepository.AdicionarQuantidadeAsync(produtoEstoque);
Esse método apenas adiciona quantidade ou insere um novo produto estoque. 
Talvez seja melhor alterar o nome se for o caso.

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoRepository.cs
> +            var produtoEstoque = await _context.ProdutosEstoques.FirstOrDefaultAsync(pe => pe.ProdutoId == idProduto && pe.EstoqueId == estoqueId);
A variável `produtoEstoque` parece não estar sendo usada

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoRepository.cs
> +            var produtoQuantidade = await _context.ProdutosEstoques.FirstOrDefaultAsync(pq => pq.ProdutoId == idProduto && pq.EstoqueId == idEstoque);
```suggestion
            var produtoEstoque = await _context.ProdutosEstoques.FirstOrDefaultAsync(pq => pq.ProdutoId == idProduto && pq.EstoqueId == idEstoque);
```

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +            var produto = await _context.ProdutosEstoques.FirstOrDefaultAsync(qP => qP.ProdutoId == idProduto && qP.EstoqueId == idEstoque);
```suggestion
            var produtoEstoque = await _context.ProdutosEstoques.FirstOrDefaultAsync(qP => qP.ProdutoId == idProduto && qP.EstoqueId == idEstoque);
```

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +            var produto = await _context.ProdutosEstoques.FirstOrDefaultAsync(pe => pe.ProdutoId == produtoEstoque.ProdutoId && pe.EstoqueId == produtoEstoque.EstoqueId);
```suggestion
            var produtoEstoque = await _context.ProdutosEstoques.FirstOrDefaultAsync(pe => pe.ProdutoId == produtoEstoque.ProdutoId && pe.EstoqueId == produtoEstoque.EstoqueId);
```

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +            var produto = await _context.ProdutosEstoques.FirstOrDefaultAsync(pq => pq.ProdutoId == idProduto && pq.EstoqueId == idEstoque);
```suggestion
            var produtoEstoque = await _context.ProdutosEstoques.FirstOrDefaultAsync(pq => pq.ProdutoId == idProduto && pq.EstoqueId == idEstoque);
```

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Repositories/ProdutoEstoqueRepository.cs
> +        public async Task<ProdutoEstoque> BuscarQuantidadePorIdEstoqueEhIdProdutoAsync(int idProduto, int idEstoque)
Ajustar o nome do método porque ele retorna um produto estoque ao invés de apenas a quantidade

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/ProdutoController.cs
> +                    var quantidade = await _produtoEstoqueRepository.BuscarQuantidadePorIdEstoqueEhIdProdutoAsync(id, idEstoque);
```suggestion
                    var produtoEstoque= await _produtoEstoqueRepository.BuscarQuantidadePorIdEstoqueEhIdProdutoAsync(id, idEstoque);
```

2025-01-15 11:35 UTC, mayconfsousa commented on GestorDeEstoque/bruno/Atualizar produto.bru
> +  url: {{URL_PADRAO}}/produtos/48/estoqueId/1
Como tudo é baseado em estoque agora, faria mais sentido ter apenas um controller EstoqueController, dessa forma as rotas irão ficar mais lógicas:

```
GET /estoques - Listar todos os estoques.
GET /estoques/{id} - Obter informações detalhadas de um estoque específico.
POST /estoques - Criar um novo estoque.
PUT /estoques/{id} - Atualizar informações de um estoque existente.
DELETE /estoques/{id} - Remover um estoque.
GET /estoques/{id}/logs - Listar os logs relacionados a um estoque.
GET /estoques/{idEstoque}/produtos - Listar todos os produtos de um estoque.
GET /estoques/{idEstoque}/produtos/{idProduto} - Obter informações detalhadas de um produto específico em um estoque.
POST /estoques/{idEstoque}/produtos - Adicionar um novo produto ao estoque.
PUT /estoques/{idEstoque}/produtos/{idProduto} - Atualizar informações de um produto em um estoque.
PATCH /estoques/{idEstoque}/produtos/{idProduto}/quantidade - Atualizar a quantidade de um produto específico em um estoque.
DELETE /estoques/{idEstoque}/produtos/{idProduto} - Remover um produto de um estoque.
```

2025-01-17 01:36 UTC, AndreLFernandesDev commented on GestorDeEstoque/Repositories/ProdutoRepository.cs
> +            var produtoEstoque = await _context.ProdutosEstoques.FirstOrDefaultAsync(pe => pe.ProdutoId == idProduto && pe.EstoqueId == estoqueId);
É usada para verificar se o produto existe naquele estoque, não precisa?

2025-01-17 13:06 UTC, mayconfsousa approved these changes

2025-01-17 13:06 UTC, merged