feat: Configuração inicial do EF Core, serviço de contexto e ajustes no gitignore
AndreLFernandesDev/GestorDeEstoque pull request #4
Opened 2024-08-09 15:26 UTC by AndreLFernandesDev

2024-08-09 18:15 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
> +var builderDb = WebApplication.CreateBuilder(args);
Eu vi que tem duas chamadas dessa

```cs
WebApplication.CreateBuilder(args)
```

Não daria para usar apenas uma delas?

2024-08-09 18:15 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
>  {
Você deveria conseguir usar o entity framework aqui, por exemplo.
Retornar algum dado de alguma tabela.
Para essa tarefa seria importante você já ter uma tabela de teste (1 coluna, por exemplo), migration, etc. Para garantir que a conexão com o banco está tudo ok para ser usada, inclusive em outros arquivos.

2024-08-09 18:16 UTC, mayconfsousa commented
> … classe de contexto de conexão, configurado serviço de contexto e removido arquivo git'appsettings.Development.json' do controle de versão e adicionado ao .gitignore

Eu vi que o commit ficou com o texto muito grande. 
Aí quando você criou o PR uma parte do commit virou o nome do PR e outra parte ficou na descrição.

2024-08-15 13:13 UTC, mayconfsousa reviewed
Adicionei alguns comentários.

Quando terminar, atualize o app bruno com as novas rotas e removendo as que foram deletadas

2024-08-15 13:13 UTC, mayconfsousa commented on GestorDeEstoque/Models/User.cs
O arquivo deveria chamar `Users` igual o nome da classe.
Só questão de padrão mesmo.

2024-08-15 13:13 UTC, mayconfsousa commented on GestorDeEstoque/Models/User.cs
> +      Name = name ?? throw new ArgumentNullException(nameof(name));
Acho que pode tirar essa validação de valor nulo de Name.
Todos os outros campos são obrigatórios também.
E o construtor já não vai deixar você passar nulo.

2024-08-15 13:13 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/UserController.cs
> +        private ApplicationDbContext _db;
O controller não deveria chamar o DbContext direto, deveria chamar o repository (ou service se tiver)

Controller -> Repository -> Banco

2024-08-15 13:19 UTC, mayconfsousa requested changes
Você pode só atualizar a estrutura de pastas para:

Controllers/
  OK
Data/
  ApplicationDbContext.cs
Migrations/
  OK
Models/
  User.cs
Repositories/
  IUserRepository.cs
  UserRepostiroy.cs

2024-08-15 13:19 UTC, mayconfsousa commented on GestorDeEstoque/Models/User.cs
> +  public class Users
A classe deveria chamar User igual o nome do arquivo.
Só questão de padrão mesmo.

```suggestion
  public class User
```

2024-08-15 13:22 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
> +    });
O que essa alteração está fazendo?

2024-08-15 13:22 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
> -builder.Services.AddEndpointsApiExplorer();
Qual o motivo de remover essa linha?

2024-08-17 01:20 UTC, AndreLFernandesDev commented on GestorDeEstoque/Program.cs
> +    });
O código configura o Swagger UI, permite a visualização e teste interativo dos endpoints da API. Isso facilita o acesso e uso da documentação da API durante o desenvolvimento e testes.

2024-08-19 18:45 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
> +    });
Já tinha uma chamada de Swagger antes, só confirma se já não era suficiente

2024-08-19 18:54 UTC, mayconfsousa requested changes

2024-08-19 18:54 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/UserController.cs
> +        private ApplicationDbContext _db;
Eu vi que vc alterou o nome da classe de UserController para UserRepository. 
O que eu quis dizer no comentário é que o controller deve chamar (no sentido de invocar) o repository ao invés de invoicar o db context direto.

2024-08-19 18:56 UTC, mayconfsousa commented
> > … classe de contexto de conexão, configurado serviço de contexto e removido arquivo git'appsettings.Development.json' do controle de versão e adicionado ao .gitignore
> 
> Eu vi que o commit ficou com o texto muito grande. Aí quando você criou o PR uma parte do commit virou o nome do PR e outra parte ficou na descrição.

Dá uma olhada nesse comentário

2024-08-19 18:56 UTC, mayconfsousa commented
> Adicionei alguns comentários.
> 
> Quando terminar, atualize o app bruno com as novas rotas e removendo as que foram deletadas

E nesse comentário

2024-08-19 19:00 UTC, mayconfsousa requested changes

2024-08-19 19:00 UTC, mayconfsousa commented on GestorDeEstoque/Data/ApplicationDbContext.cs
> +namespace GestorDeEstoque.Repositories
Aqui deveria ser

```suggestion
namespace GestorDeEstoque.Data
```

2024-08-19 19:00 UTC, mayconfsousa commented on GestorDeEstoque/Models/User.cs
> +namespace GestorDeEstoque.Repositories
Aqui deveria ser

```suggestion
namespace GestorDeEstoque.Models
```

2024-08-22 01:03 UTC, AndreLFernandesDev commented on GestorDeEstoque/Program.cs
> +    });
Pelo que pesquisei aqui faz sentido ter as duas, fala que uma cria o documento json e a outra a interface

2024-08-23 02:40 UTC, mayconfsousa requested changes

2024-08-23 02:40 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/UserController.cs
> +    public class UserControlers : ControllerBase
```suggestion
    public class UserController : ControllerBase
```

2024-08-23 02:40 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/UserController.cs
> +        public UserControlers(UserRepository db)
```suggestion
        public UserController(UserRepository db)
```

2024-08-23 02:40 UTC, mayconfsousa commented on GestorDeEstoque/Program.cs
> +    });
Você chegou a testar do jeito que era antes?
Eu testei aqui o Swagger apareceu normalmente.

2024-08-23 02:41 UTC, mayconfsousa commented
Está dando essa mensagem aqui para mim

<img width="861" alt="Screenshot 2024-08-22 at 23 39 56" src="https://github.com/user-attachments/assets/bf9ce9e7-7e83-4b02-a8f9-ebdf094359b8">

2024-08-23 02:51 UTC, mayconfsousa requested changes

2024-08-23 02:51 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/UserController.cs
> +        private UserRepository _db;
```suggestion
        private UserRepository _userRepository;
```

2024-08-23 02:51 UTC, mayconfsousa commented on GestorDeEstoque/bruno/GET.bru
> +}
Está faltando a chamada da nova rota de API criada
`/users`

2024-08-25 11:17 UTC, mayconfsousa approved these changes

2024-08-25 11:18 UTC, merged