Feature/inv 9 criar endpoint para listar produtos
AndreLFernandesDev/GestorDeEstoque pull request #9
Opened 2024-10-01 02:11 UTC by AndreLFernandesDev

2024-10-01 02:12 UTC, AndreLFernandesDev commented
Se possível, dê uma olhada nas mensagens de commits, fazem sentido?

2024-10-02 21:22 UTC, mayconfsousa requested changes

2024-10-02 21:22 UTC, mayconfsousa commented on GestorDeEstoque/Controllers/ProdutoController.cs
> +            var produtos = await _produtoRepository.ListarProdutos();
Como essa linha está de fora do `try/catch`, se acontecer um erro o retorno não vai ser tratado como você implementou no `catch`.
Você pode tentar mudar a URL do banco de dados, colocando alguma coisa errada, para simular o erro.

2024-10-02 21:22 UTC, mayconfsousa commented on GestorDeEstoque/bruno/Listar Produtos.bru
> +  url:
Você chegou a testar a chamada pelo app Bruno?
Não tem URL 🤔

2024-10-03 14:26 UTC, AndreLFernandesDev commented on GestorDeEstoque/bruno/Listar Produtos.bru
> +  url:
sim, chamei assim, "{{URL_PADRAO}}/produtos", mas observei aqui mesmo, devo ter me esquecido de salvar

2024-10-03 14:29 UTC, AndreLFernandesDev commented on GestorDeEstoque/Controllers/ProdutoController.cs
> +            var produtos = await _produtoRepository.ListarProdutos();
Ah sim, se ocorrer um erro ao chamar o banco, por exemplo, já quebraria né? Vou ajustar

2024-10-03 14:51 UTC, mayconfsousa approved these changes

2024-10-03 14:51 UTC, merged